export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'
export const GET_ALL_POST_RESET = 'GET_ALL_POST_RESET'

export const UPDATE_LIKE_SUCCESS = 'UPDATE_LIKE_SUCCESS'
export const UPDATE_LIKE_FAIL = 'UPDATE_LIKE_FAIL'

export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS'
export const DELETE_POST_FAIL = 'DELETE_POST_FAIL'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'
export const CREATE_POST_RESET = 'CREATE_POST_RESET'

export const SINGLE_POST_REQUEST = 'SINGLE_POST_REQUEST'
export const SINGLE_POST_SUCCESS = 'SINGLE_POST_SUCCESS'
export const SINGLE_POST_FAIL = 'SINGLE_POST_FAIL'
export const SINGLE_POST_RESET = 'SINGLE_POST_RESET'
