export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'
export const GET_ALL_POST_RESET = 'GET_ALL_POST_RESET'
