export const CURRENT_USER_PROFILE_REQUEST = 'CURRENT_USER_PROFILE_REQUEST'
export const CURRENT_USER_PROFILE_SUCCESS = 'CURRENT_USER_PROFILE_SUCCESS'
export const CURRENT_USER_PROFILE_FAIL = 'CURRENT_USER_PROFILE_FAIL'
export const CURRENT_USER_PROFILE_RESET = 'CURRENT_USER_PROFILE_RESET'

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL'
export const CREATE_PROFILE_RESET = 'CREATE_PROFILE_RESET'

export const ADD_EXPERIENCE_REQUEST = 'ADD_EXPERIENCE_REQUEST'
export const ADD_EXPERIENCE_SUCCESS = 'ADD_EXPERIENCE_SUCCESS'
export const ADD_EXPERIENCE_FAIL = 'ADD_EXPERIENCE_FAIL'
export const ADD_EXPERIENCE_RESET = 'ADD_EXPERIENCE_RESET'

export const ADD_EDUCATION_REQUEST = 'ADD_EDUCATION_REQUEST'
export const ADD_EDUCATION_SUCCESS = 'ADD_EDUCATION_SUCCESS'
export const ADD_EDUCATION_FAIL = 'ADD_EDUCATION_FAIL'
export const ADD_EDUCATION_RESET = 'ADD_EDUCATION_RESET'

export const DELETE_EXPERIENCE_REQUEST = 'DELETE_EXPERIENCE_REQUEST'
export const DELETE_EXPERIENCE_SUCCESS = 'DELETE_EXPERIENCE_SUCCESS'
export const DELETE_EXPERIENCE_FAIL = 'DELETE_EXPERIENCE_FAIL'
export const DELETE_EXPERIENCE_RESET = 'DELETE_EXPERIENCE_RESET'

export const DELETE_EDUCATION_REQUEST = 'DELETE_EDUCATION_REQUEST'
export const DELETE_EDUCATION_SUCCESS = 'DELETE_EDUCATION_SUCCESS'
export const DELETE_EDUCATION_FAIL = 'DELETE_EDUCATION_FAIL'
export const DELETE_EDUCATION_RESET = 'DELETE_EDUCATION_RESET'

export const DELETE_ACCOUNT_REQUEST = 'DELETE_ACCOUNT_REQUEST'
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS'
export const DELETE_ACCOUNT_FAIL = 'DELETE_ACCOUNT_FAIL'
export const DELETE_ACCOUNT_RESET = 'DELETE_ACCOUNT_RESET'
