export const CURRENT_USER_PROFILE_REQUEST = 'CURRENT_USER_PROFILE_REQUEST'
export const CURRENT_USER_PROFILE_SUCCESS = 'CURRENT_USER_PROFILE_SUCCESS'
export const CURRENT_USER_PROFILE_FAIL = 'CURRENT_USER_PROFILE_FAIL'
export const CURRENT_USER_PROFILE_RESET = 'CURRENT_USER_PROFILE_RESET'
