export const CURRENT_USER_PROFILE_REQUEST = 'CURRENT_USER_PROFILE_REQUEST'
export const CURRENT_USER_PROFILE_SUCCESS = 'CURRENT_USER_PROFILE_SUCCESS'
export const CURRENT_USER_PROFILE_FAIL = 'CURRENT_USER_PROFILE_FAIL'
export const CURRENT_USER_PROFILE_RESET = 'CURRENT_USER_PROFILE_RESET'

export const CREATE_PROFILE_REQUEST = 'CREATE_PROFILE_REQUEST'
export const CREATE_PROFILE_SUCCESS = 'CREATE_PROFILE_SUCCESS'
export const CREATE_PROFILE_FAIL = 'CREATE_PROFILE_FAIL'
export const CREATE_PROFILE_RESET = 'CREATE_PROFILE_RESET'
